// Generated by CoffeeScript 1.8.0
(function() {
    var domain = require("domain");
    var libpath = process.env['BUGSNAG_COV'] ? '../lib-cov/' : '../lib/';
    should = require("chai").should();
    sinon = require("sinon");
    Bugsnag = require(libpath + "bugsnag");
    Notification = require(libpath + "notification");
    apiKey = null;
    deliverStub = null;

    before(function() {
        apiKey = "71ab53572c7b45316fb894d496f2e11d";
        return Bugsnag.register(apiKey, {
            notifyReleaseStages: ["production", "development"]
        });
    });

    describe("Bugsnag", function() {

        beforeEach(function() {
            return deliverStub = sinon.stub(Notification.prototype, "deliver");
        });

        afterEach(function() {
            return Notification.prototype.deliver.restore();
        });

        it("should call deliver when notifying a caught error", function() {
            var e;
            try {
                throw new Error("This is the message");
            } catch (_error) {
                e = _error;
                Bugsnag.notify(e);
            }
            return deliverStub.calledOnce.should.equal(true);
        });

        it("should call deliver when notifying an event emitter error", function() {
            var eventEmitter = new (require('events').EventEmitter)();
            eventEmitter.on("error", Bugsnag.notify);
            eventEmitter.emit("error", "Something went wrong");
            deliverStub.calledOnce.should.equal(true);
        });

        it("stores metadata", function() {
            Bugsnag.metaData.red = "23";
            Bugsnag.metaData.red.should.equal("23");
        });

        it("stores request data when domain is set", function() {
            process.domain = {};
            var requestData = { method: "POST", path: "/" };
            Bugsnag.requestData = requestData;
            Bugsnag.requestData.should.equal(requestData);
            process.domain = null;
        });

        it("discards request data when domain is unset", function() {
            var requestData = { method: "POST", path: "/" };
            Bugsnag.requestData = requestData;
            Bugsnag.should.not.have.property(requestData)
        });

        it("should call deliver when notifying with a domain, using event emitter", function() {
            var mainDomain;
            mainDomain = domain.create();
            mainDomain.on("error", Bugsnag.notify);
            mainDomain.run(function() {
                var eventEmitter = new (require('events').EventEmitter)();
                eventEmitter.emit("error", new Error("Something went wrong"));
            });
            deliverStub.calledOnce.should.equal(true);
        });

        it("should expose requestData when inside a domain and using user.id", function () {
            var mainDomain;
            mainDomain = domain.create();
            mainDomain.on("error", Bugsnag.notify);
            mainDomain.run(function() {
                Bugsnag.requestData = {user: {id: 5}};
                var eventEmitter = new (require('events').EventEmitter)();
                eventEmitter.emit("error", new Error("Something went wrong"));
            });
            deliverStub.calledOnce.should.equal(true);
            deliverStub.firstCall.thisValue.events[0].user.id.should.equal(5);
        });

        it("should expose requestData when inside a domain using userId", function () {
            var mainDomain;
            mainDomain = domain.create();
            mainDomain.on("error", Bugsnag.notify);
            mainDomain.run(function() {
                Bugsnag.requestData = {userId: 5};
                var eventEmitter = new (require('events').EventEmitter)();
                eventEmitter.emit("error", new Error("Something went wrong"));
            });
            deliverStub.calledOnce.should.equal(true);
            deliverStub.firstCall.thisValue.events[0].user.id.should.equal(5);
        });
    });

    describe("Bugsnag", function() {

        describe("Notification.deliver", function() {
            it("should call the callback after notifying bugsnag", function(done) {
                Bugsnag.notify("error message", done);
            });

            it("should call callback when releaseStage isnt configured in notifyReleaseStages", function(done) {

                var oldNotifyReleaseStagesValue;
                oldNotifyReleaseStagesValue = Bugsnag.notifyReleaseStages;
                Bugsnag.notifyReleaseStages = ["production"];
                Bugsnag.notify("This is the message", done);
                Bugsnag.notifyReleaseStages = oldNotifyReleaseStagesValue;
            });
        });
    });

}).call(this);
