// Generated by CoffeeScript 1.8.0
(function() {
  var Bugsnag, BugsnagError, apiKey, deliverStub, path, should, sinon;

  path = require("path");

  should = require("chai").should();

  sinon = require("sinon");

  Bugsnag = require("../");

  BugsnagError = require("../lib/error");

  apiKey = null;

  deliverStub = null;

  before(function() {
    apiKey = "71ab53572c7b45316fb894d446f2e11d";
    return Bugsnag.register(apiKey, {
      notifyReleaseStages: ["production", "development"]
    });
  });

  beforeEach(function() {
    return Bugsnag.configure({
      notifyReleaseStages: ["production", "development"]
    });
  });

  describe("Error", function() {
    it("should have one error", function() {
      var error, errors;
      error = new Error("error");
      errors = BugsnagError.buildErrors(error);
      return errors.length.should.equal(1);
    });
    it("should copy custom error props", function () {
      var error, errors, MyError;
      MyError = function(message, customProp) {
        this.message = message;
        this.customProp = customProp;
      };
      MyError.prototype = Object.create(Error.prototype);
      MyError.prototype.constructor = MyError;
      error = new MyError("error", "custom prop");
      errors = BugsnagError.buildErrors(error);
      errors.length.should.equal(1);
      return errors[0].metaData.customProp.should.equal("custom prop");
    });
    return it("should support oath errors", function() {
      var error, errors;
      error = new Error("error");
      error.oauthError = new Error("oauth error");
      errors = BugsnagError.buildErrors(error);
      return errors.length.should.equal(2);
    });
  });

}).call(this);
